List element variable
zjedi/hugo-scroll pull request #152
Opened 2023-09-28 12:02 UTC by spi43984

#151

2023-09-30 20:54 UTC, zjedi requested changes

2023-09-30 20:54 UTC, zjedi commented on assets/js/index.js
> +      $("ul li").prepend('<span class="fa-li"><i class="fa ' + listElement + '"></i></span>');
if listElement itself is `fa-asterisk`, won't this compose into `fafa-asterisk`?

2023-09-30 20:54 UTC, zjedi commented on assets/js/index.js
> +    if (listElement.length > 0) {
So if the property is undefined, there is no icon applied? Looks ok

2023-09-30 20:54 UTC, zjedi commented on assets/css/variables.scss
> +    --listElement: fa-asterisk;
I'm thinking about the name ... how about `list-icon` or `li-icon`

2023-10-01 09:14 UTC, spi43984 commented on assets/js/index.js
> +      $("ul li").prepend('<span class="fa-li"><i class="fa ' + listElement + '"></i></span>');
I hope not... Originally there is `class="fa fa-asterisk"` which is then composed to  `class="fa ' + listElement + '"` - please note the space after the initial fa.

2023-10-01 09:15 UTC, spi43984 commented on assets/js/index.js
> +    if (listElement.length > 0) {
right, that is the idea. The default "fa fa-asterisk" gets defined in variables.scss and can be changed or omitted by the user.

2023-10-01 09:16 UTC, spi43984 commented on assets/css/variables.scss
> +    --listElement: fa-asterisk;
li-icon sounds good to me - bu as this is for unnumbered lists only how about something like ul-li-icon? On the other hand numbered lists don't have any icons. So li-icon really sounds ok.

2023-10-01 10:12 UTC, zjedi commented on assets/js/index.js
> +      $("ul li").prepend('<span class="fa-li"><i class="fa ' + listElement + '"></i></span>');
ah, ok, I missed the space

2023-10-01 10:13 UTC, zjedi commented on assets/css/variables.scss
> +    --listElement: fa-asterisk;
both ul-li-icon and li-icon sound ok to me :)

2023-10-01 10:23 UTC, spi43984 commented on assets/css/variables.scss
> +    --listElement: fa-asterisk;
your code - you decide ;-)

2023-10-01 23:25 UTC, zjedi commented on assets/css/variables.scss
> +    --listElement: fa-asterisk;
ok, let's go with `ul-li-icon`, it's the most descriptive :)

2023-10-04 09:56 UTC, spi43984 commented
changes done - pls recheck

2023-10-04 15:43 UTC, spi43984 reviewed
changes done

2023-10-04 19:04 UTC, zjedi approved these changes

2023-10-04 19:06 UTC, merged