Internal links on site head
zjedi/hugo-scroll pull request #158
Opened 2023-10-04 15:36 UTC by spi43984

I needed some links on the cover page to link to internal sites and not showing the leading fork awesome icon.
For some of these pages I also wanted to get the content still rendered on the homepage - for others not.

With these changes two parameters are introduced in the markdown files:
internal = the URL to link to
internal_hide = if true then do not render this markdown file (as a side-effect this works on all homepage markdown files to show or hide them)

2023-10-04 16:53 UTC, zjedi commented on exampleSite/content/homepage/internal.md
> +title: "Link2InternalPage"
What's the use case? Linking to single, dedicated page?

2023-10-04 19:00 UTC, spi43984 commented on exampleSite/content/homepage/internal.md
> +title: "Link2InternalPage"
I needed an internal, dedicated page for detailed contact and legal information. An external link I didn't like due to the leading icon. BTW - I had to set up a 1st markdown file with an external link, then I needed the single page with the legal staff (2nd markdown file). And I wanted to have the legal stuff shortened as a section on my homepage (the 3rd markdown file), but without an additional button on the cover page (as I already had one for the dedicated page, but on the other hand I wanted a navigation menu entry for the section if the user scrolled down a little).

As I didn't like the icon for the external link button I created code for the internal link. While creating this code I figured out that I just need two markdown files - the single page and just another one with the internal link destination and the content for the section. That's why I introduced the parameter internal_hide - now I can add multiple links as buttons on the cover page and have a section on the homepage for some and not for the others.

2023-10-04 19:31 UTC, zjedi requested changes
Something seems wrong with the demo page, see deployed demo, at the very bottom. https://deploy-preview-158--hugo-scroll.netlify.app/#github
![image](https://github.com/zjedi/hugo-scroll/assets/15914748/b8f96eda-5796-4bf4-b5d7-0de1303182b9)

2023-10-05 10:19 UTC, spi43984 commented
> Something seems wrong with the demo page, see deployed demo, at the very bottom. https://deploy-preview-158--hugo-scroll.netlify.app/#github ![image](https://user-images.githubusercontent.com/15914748/272689496-b8f96eda-5796-4bf4-b5d7-0de1303182b9.png)

Added leading '---' to internal.md.

2023-10-06 23:22 UTC, zjedi approved these changes

2023-10-06 23:27 UTC, zjedi commented
@spi43984 If you go check the demo now, there are some outstanding issues
- two sections Contact + Contacts, sounds illogical to have two of them
- try navigating from landing page, from left "sticky menu", play around, I managed to run into an error.

2023-10-08 13:20 UTC, spi43984 commented
> @spi43984 If you go check the demo now, there are some outstanding issues
> 
> * two sections Contact + Contacts, sounds illogical to have two of them

fair point - as there is already a contact section, will prepare another example, maybe legal or something

> * try navigating from landing page, from left "sticky menu", play around, I managed to run into an error.

What was the error? Can you please give some more context?
Or is it GITHUB to show up in the nav menu? Which should not as it is an external link, found a bug in index.html - am trying to solve that:
```
{{ $content := where $sections "Params.external" "==" nil }}
{{ $content := where $sections "Params.internal_hide" "ne" true }}
```
The second line circumvents the first one and renders homepage content even it is an external link.

Is there a combination possible like
```
{{ $content := where $sections and ("Params.internal_hide" "ne" true) ("Params.internal_hide" "ne" true) }}
```

2023-10-08 14:31 UTC, spi43984 commented
> @spi43984 If you go check the demo now, there are some outstanding issues
> 
> * two sections Contact + Contacts, sounds illogical to have two of them
> * try navigating from landing page, from left "sticky menu", play around, I managed to run into an error.

please review

2023-10-08 21:23 UTC, zjedi commented
> two sections Contact + Contacts, sounds illogical to have two of them

Looks good now, thanks!

> try navigating from landing page, from left "sticky menu", play around, I managed to run into an error.

Unable to reproduce the error, looks ok now.

2023-10-08 21:47 UTC, zjedi requested changes
Looks good, just a couple suggestions regarding configuration property names to make them more obvious :)

2023-10-08 21:47 UTC, zjedi commented on exampleSite/content/homepage/internal.md
could this file be renamed to something like `legal-brief.md` to make it more obvious?

2023-10-08 21:47 UTC, zjedi commented on exampleSite/content/homepage/internal.md
> +internal: /legal/
Something like `detailed_page_path: /legal/` would sound more descriptive :)

then also:
`internal_hide: false` -> or `detailed_page_exclude_homepage_content: false` or maybe even better  `detailed_page_homepage_content: true` (simplify double negation)

2023-10-08 21:49 UTC, zjedi commented on exampleSite/content/homepage/internal.md
> +If `internal_hide` is set to false, the link, navigation menu and the content will be rendered. In that case thids section might contain less or just summarized information compared to the single pag
typo: thids ;)

2023-10-09 08:43 UTC, spi43984 commented on exampleSite/content/homepage/internal.md
ok

2023-10-09 08:48 UTC, spi43984 commented on exampleSite/content/homepage/internal.md
> +If `internal_hide` is set to false, the link, navigation menu and the content will be rendered. In that case thids section might contain less or just summarized information compared to the single pag
ok

2023-10-14 13:21 UTC, zjedi approved these changes

2023-10-14 13:23 UTC, merged